name: Schecule Tests

on:
  schedule:
    # 1° minuto(0-59) / 2° hora (0-23)/ 3° dia do mês(1-31) / 4° mês(1-12) /
    # 5° dia da semana(1-6 ou SUN-SAT)/ * signfica todos
    - cron: '30 * * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4


      - name: Instalar java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar o chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar o chromedriver
        uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


      - name: Run test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-tests
          path: '**/formated-report/'
